/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dados.AppDao;
import dados.Item;
import dados.Utilitarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class CriarItem extends javax.swing.JFrame {

    /**
     * Creates new form CriarItem
     */
    private int idVendedor;

    public CriarItem() {
        initComponents();
    }

    public CriarItem(int id) {
        initComponents();
        this.idVendedor = id;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelItem = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jlQtdItensNaLoja = new javax.swing.JLabel();
        jComboBoxQtd = new javax.swing.JComboBox<>();
        jPanelItem1 = new javax.swing.JPanel();
        jlTitulo1 = new javax.swing.JLabel();
        jlNomeItem1 = new javax.swing.JLabel();
        jTextNomeLoja1 = new javax.swing.JTextField();
        jlMiniDescricao1 = new javax.swing.JLabel();
        jTextMiniDescricao1 = new javax.swing.JTextField();
        jlDescricao1 = new javax.swing.JLabel();
        jTextDescricao1 = new javax.swing.JTextField();
        jlValidade1 = new javax.swing.JLabel();
        jTextValidade1 = new javax.swing.JTextField();
        jlQtd1 = new javax.swing.JLabel();
        jTextQtd1 = new javax.swing.JTextField();
        jlPreco1 = new javax.swing.JLabel();
        jTextPreco1 = new javax.swing.JTextField();
        jPanelItem2 = new javax.swing.JPanel();
        jlTitulo2 = new javax.swing.JLabel();
        jlNomeItem2 = new javax.swing.JLabel();
        jTextNomeLoja2 = new javax.swing.JTextField();
        jlMiniDescricao2 = new javax.swing.JLabel();
        jTextMiniDescricao2 = new javax.swing.JTextField();
        jlDescricao2 = new javax.swing.JLabel();
        jTextDescricao2 = new javax.swing.JTextField();
        jlValidade2 = new javax.swing.JLabel();
        jTextValidade2 = new javax.swing.JTextField();
        jlQtd2 = new javax.swing.JLabel();
        jTextQtd2 = new javax.swing.JTextField();
        jlPreco2 = new javax.swing.JLabel();
        jTextPreco2 = new javax.swing.JTextField();
        jPanelItem3 = new javax.swing.JPanel();
        jlTitulo3 = new javax.swing.JLabel();
        jlNomeItem3 = new javax.swing.JLabel();
        jTextNomeLoja3 = new javax.swing.JTextField();
        jlMiniDescricao3 = new javax.swing.JLabel();
        jTextMiniDescricao3 = new javax.swing.JTextField();
        jlDescricao3 = new javax.swing.JLabel();
        jTextDescricao3 = new javax.swing.JTextField();
        jlValidade3 = new javax.swing.JLabel();
        jTextValidade3 = new javax.swing.JTextField();
        jlQtd3 = new javax.swing.JLabel();
        jTextQtd3 = new javax.swing.JTextField();
        jlPreco3 = new javax.swing.JLabel();
        jTextPreco3 = new javax.swing.JTextField();
        jPanelItem4 = new javax.swing.JPanel();
        jlTitulo4 = new javax.swing.JLabel();
        jlNomeItem4 = new javax.swing.JLabel();
        jTextNomeLoja4 = new javax.swing.JTextField();
        jlMiniDescricao4 = new javax.swing.JLabel();
        jTextMiniDescricao4 = new javax.swing.JTextField();
        jlDescricao4 = new javax.swing.JLabel();
        jTextDescricao4 = new javax.swing.JTextField();
        jlValidade4 = new javax.swing.JLabel();
        jTextValidade4 = new javax.swing.JTextField();
        jlQtd4 = new javax.swing.JLabel();
        jTextQtd4 = new javax.swing.JTextField();
        jlPreco4 = new javax.swing.JLabel();
        jTextPreco4 = new javax.swing.JTextField();
        jPanelItem5 = new javax.swing.JPanel();
        jlTitulo5 = new javax.swing.JLabel();
        jlNomeItem5 = new javax.swing.JLabel();
        jTextNomeLoja5 = new javax.swing.JTextField();
        jlMiniDescricao5 = new javax.swing.JLabel();
        jTextMiniDescricao5 = new javax.swing.JTextField();
        jlDescricao5 = new javax.swing.JLabel();
        jTextDescricao5 = new javax.swing.JTextField();
        jlValidade5 = new javax.swing.JLabel();
        jTextValidade5 = new javax.swing.JTextField();
        jlQtd5 = new javax.swing.JLabel();
        jTextQtd5 = new javax.swing.JTextField();
        jlPreco5 = new javax.swing.JLabel();
        jTextPreco5 = new javax.swing.JTextField();
        jPanelItem6 = new javax.swing.JPanel();
        jlTitulo6 = new javax.swing.JLabel();
        jlNomeItem6 = new javax.swing.JLabel();
        jTextNomeLoja6 = new javax.swing.JTextField();
        jlMiniDescricao6 = new javax.swing.JLabel();
        jTextMiniDescricao6 = new javax.swing.JTextField();
        jlDescricao6 = new javax.swing.JLabel();
        jTextDescricao6 = new javax.swing.JTextField();
        jlValidade6 = new javax.swing.JLabel();
        jTextValidade6 = new javax.swing.JTextField();
        jlQtd6 = new javax.swing.JLabel();
        jTextQtd6 = new javax.swing.JTextField();
        jlPreco6 = new javax.swing.JLabel();
        jTextPreco6 = new javax.swing.JTextField();
        btnCadastrarItens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelItem.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/LOGO.png"))); // NOI18N

        jlQtdItensNaLoja.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlQtdItensNaLoja.setForeground(new java.awt.Color(0, 51, 102));
        jlQtdItensNaLoja.setText("Quantidade de itens:");

        jComboBoxQtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBoxQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQtdActionPerformed(evt);
            }
        });

        jlTitulo1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo1.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo1.setText("Criar item 1");

        jlNomeItem1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem1.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem1.setText("  Nome Produto:");

        jlMiniDescricao1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao1.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao1.setText("Mini Descrição:");

        jlDescricao1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao1.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao1.setText("        Descrição:");

        jlValidade1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade1.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade1.setText("          Validade:");

        jlQtd1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd1.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd1.setText("      Quantidade:");

        jlPreco1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco1.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco1.setText("                Preço:");

        jTextPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPreco1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItem1Layout = new javax.swing.GroupLayout(jPanelItem1);
        jPanelItem1.setLayout(jPanelItem1Layout);
        jPanelItem1Layout.setHorizontalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItem1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco1)
                            .addComponent(jlQtd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem1Layout.setVerticalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addComponent(jlTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem1)
                    .addComponent(jTextNomeLoja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao1)
                    .addComponent(jTextMiniDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao1)
                    .addComponent(jTextDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade1)
                    .addComponent(jTextValidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd1)
                    .addComponent(jTextQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco1)
                    .addComponent(jTextPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelItem2.setVisible(false);

        jlTitulo2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo2.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo2.setText("Criar item 2");

        jlNomeItem2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem2.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem2.setText("  Nome Da Loja:");

        jlMiniDescricao2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao2.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao2.setText("Mini Descrição:");

        jlDescricao2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao2.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao2.setText("        Descrição:");

        jlValidade2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade2.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade2.setText("          Validade:");

        jlQtd2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd2.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd2.setText("      Quantidade:");

        jlPreco2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco2.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco2.setText("                Preço:");

        javax.swing.GroupLayout jPanelItem2Layout = new javax.swing.GroupLayout(jPanelItem2);
        jPanelItem2.setLayout(jPanelItem2Layout);
        jPanelItem2Layout.setHorizontalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItem2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco2)
                            .addComponent(jlQtd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem2Layout.setVerticalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addComponent(jlTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem2)
                    .addComponent(jTextNomeLoja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao2)
                    .addComponent(jTextMiniDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao2)
                    .addComponent(jTextDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade2)
                    .addComponent(jTextValidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd2)
                    .addComponent(jTextQtd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco2)
                    .addComponent(jTextPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelItem3.setVisible(false);

        jlTitulo3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo3.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo3.setText("Criar item 3");

        jlNomeItem3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem3.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem3.setText("  Nome Da Loja:");

        jlMiniDescricao3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao3.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao3.setText("Mini Descrição:");

        jlDescricao3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao3.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao3.setText("        Descrição:");

        jlValidade3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade3.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade3.setText("          Validade:");

        jlQtd3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd3.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd3.setText("      Quantidade:");

        jlPreco3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco3.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco3.setText("                Preço:");

        javax.swing.GroupLayout jPanelItem3Layout = new javax.swing.GroupLayout(jPanelItem3);
        jPanelItem3.setLayout(jPanelItem3Layout);
        jPanelItem3Layout.setHorizontalGroup(
            jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem3Layout.createSequentialGroup()
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem3Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItem3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco3)
                            .addComponent(jlQtd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem3Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem3Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem3Layout.setVerticalGroup(
            jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem3Layout.createSequentialGroup()
                .addComponent(jlTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem3)
                    .addComponent(jTextNomeLoja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao3)
                    .addComponent(jTextMiniDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao3)
                    .addComponent(jTextDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade3)
                    .addComponent(jTextValidade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd3)
                    .addComponent(jTextQtd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco3)
                    .addComponent(jTextPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelItem4.setVisible(false);

        jlTitulo4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo4.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo4.setText("Criar item 4");

        jlNomeItem4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem4.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem4.setText("  Nome Da Loja:");

        jlMiniDescricao4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao4.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao4.setText("Mini Descrição:");

        jlDescricao4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao4.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao4.setText("        Descrição:");

        jlValidade4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade4.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade4.setText("          Validade:");

        jlQtd4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd4.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd4.setText("      Quantidade:");

        jlPreco4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco4.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco4.setText("                Preço:");

        javax.swing.GroupLayout jPanelItem4Layout = new javax.swing.GroupLayout(jPanelItem4);
        jPanelItem4.setLayout(jPanelItem4Layout);
        jPanelItem4Layout.setHorizontalGroup(
            jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem4Layout.createSequentialGroup()
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco4)
                            .addComponent(jlQtd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem4Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem4Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelItem4Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem4Layout.setVerticalGroup(
            jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem4Layout.createSequentialGroup()
                .addComponent(jlTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem4)
                    .addComponent(jTextNomeLoja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao4)
                    .addComponent(jTextMiniDescricao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao4)
                    .addComponent(jTextDescricao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade4)
                    .addComponent(jTextValidade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd4)
                    .addComponent(jTextQtd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco4)
                    .addComponent(jTextPreco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelItem5.setVisible(false);

        jlTitulo5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo5.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo5.setText("Criar item 5");

        jlNomeItem5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem5.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem5.setText("  Nome Da Loja:");

        jlMiniDescricao5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao5.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao5.setText("Mini Descrição:");

        jlDescricao5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao5.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao5.setText("        Descrição:");

        jlValidade5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade5.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade5.setText("          Validade:");

        jlQtd5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd5.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd5.setText("      Quantidade:");

        jlPreco5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco5.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco5.setText("                Preço:");

        javax.swing.GroupLayout jPanelItem5Layout = new javax.swing.GroupLayout(jPanelItem5);
        jPanelItem5.setLayout(jPanelItem5Layout);
        jPanelItem5Layout.setHorizontalGroup(
            jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem5Layout.createSequentialGroup()
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco5)
                            .addComponent(jlQtd5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem5Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem5Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelItem5Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem5Layout.setVerticalGroup(
            jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem5Layout.createSequentialGroup()
                .addComponent(jlTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem5)
                    .addComponent(jTextNomeLoja5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao5)
                    .addComponent(jTextMiniDescricao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao5)
                    .addComponent(jTextDescricao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade5)
                    .addComponent(jTextValidade5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd5)
                    .addComponent(jTextQtd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco5)
                    .addComponent(jTextPreco5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelItem6.setVisible(false);

        jlTitulo6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo6.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo6.setText("Criar item 6");

        jlNomeItem6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeItem6.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeItem6.setText("  Nome Da Loja:");

        jlMiniDescricao6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricao6.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricao6.setText("Mini Descrição:");

        jlDescricao6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDescricao6.setForeground(new java.awt.Color(0, 51, 102));
        jlDescricao6.setText("        Descrição:");

        jlValidade6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValidade6.setForeground(new java.awt.Color(0, 51, 102));
        jlValidade6.setText("          Validade:");

        jlQtd6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd6.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd6.setText("      Quantidade:");

        jlPreco6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlPreco6.setForeground(new java.awt.Color(0, 51, 102));
        jlPreco6.setText("                Preço:");

        javax.swing.GroupLayout jPanelItem6Layout = new javax.swing.GroupLayout(jPanelItem6);
        jPanelItem6.setLayout(jPanelItem6Layout);
        jPanelItem6Layout.setHorizontalGroup(
            jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem6Layout.createSequentialGroup()
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeItem6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescricao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlPreco6)
                            .addComponent(jlQtd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlValidade6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItem6Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescricao6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextValidade6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextQtd6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreco6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem6Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextMiniDescricao6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomeLoja6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelItem6Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelItem6Layout.setVerticalGroup(
            jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem6Layout.createSequentialGroup()
                .addComponent(jlTitulo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem6)
                    .addComponent(jTextNomeLoja6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricao6)
                    .addComponent(jTextMiniDescricao6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao6)
                    .addComponent(jTextDescricao6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValidade6)
                    .addComponent(jTextValidade6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd6)
                    .addComponent(jTextQtd6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco6)
                    .addComponent(jTextPreco6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnCadastrarItens.setBackground(new java.awt.Color(51, 153, 0));
        btnCadastrarItens.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCadastrarItens.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarItens.setText("Cadastrar Itens");
        btnCadastrarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarItensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItemLayout = new javax.swing.GroupLayout(jPanelItem);
        jPanelItem.setLayout(jPanelItemLayout);
        jPanelItemLayout.setHorizontalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelItemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItemLayout.createSequentialGroup()
                        .addContainerGap(155, Short.MAX_VALUE)
                        .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelItemLayout.createSequentialGroup()
                        .addComponent(jlQtdItensNaLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelItemLayout.setVerticalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQtdItensNaLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCadastrarItens)
                .addGap(1012, 1012, 1012))
        );

        jScrollPane1.setViewportView(jPanelItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarItensActionPerformed

        try {

            Item item = null;
            boolean item1 = false, item2 = false, item3 = false, item4 = false, item5 = false, item6 = false;
            int ctd = 0;

            int qtdItem = Integer.parseInt(jComboBoxQtd.getSelectedItem().toString());

            for (int i = 1; i <= qtdItem; i++) {

                // item 1
                if (i == 1 && item1 == false) {
                    String nomeProduto1 = jTextNomeLoja1.getText();
                    String miniDescricaoProduto1 = jTextMiniDescricao1.getText();
                    String descricaoProduto1 = jTextDescricao1.getText();
                    String validade1 = jTextValidade1.getText();
                    int qtdProduto1 = 0;
                    double preco1 = 0;

                    if (nomeProduto1.length() > 0 && miniDescricaoProduto1.length() > 0 && descricaoProduto1.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade1)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd1.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco1.getText())) {

                                    qtdProduto1 = Integer.parseInt(jTextQtd1.getText());
                                    preco1 = Double.parseDouble(jTextPreco1.getText());

                                    item = new Item(nomeProduto1, miniDescricaoProduto1, descricaoProduto1, validade1, qtdProduto1, preco1);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item1 = true;
                                    ctd++;
                                    jTextNomeLoja1.setText("");// apagar cambo txt
                                    jTextMiniDescricao1.setText("");
                                    jTextDescricao1.setText("");
                                    jTextValidade1.setText("");
                                    jTextQtd1.setText("");
                                    jTextNomeLoja1.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }
                //item 2
                if (i == 2 && item2 == false) {
                    String nomeProduto2 = jTextNomeLoja2.getText();
                    String miniDescricaoProduto2 = jTextMiniDescricao2.getText();
                    String descricaoProduto2 = jTextDescricao2.getText();
                    String validade2 = jTextValidade2.getText();
                    int qtdProduto2 = 0;
                    double preco2 = 0;

                    if (nomeProduto2.length() > 0 && miniDescricaoProduto2.length() > 0 && descricaoProduto2.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade2)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd2.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco2.getText())) {

                                    qtdProduto2 = Integer.parseInt(jTextQtd2.getText());
                                    preco2 = Double.parseDouble(jTextPreco2.getText());

                                    item = new Item(nomeProduto2, miniDescricaoProduto2, descricaoProduto2, validade2, qtdProduto2, preco2);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item2 = true;
                                    ctd++;
                                    jTextNomeLoja2.setText("");// apagar cambo txt
                                    jTextMiniDescricao2.setText("");
                                    jTextDescricao2.setText("");
                                    jTextValidade2.setText("");
                                    jTextQtd2.setText("");
                                    jTextNomeLoja2.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }

                //item 3
                if (i == 3 && item3 == false) {
                    String nomeProduto3 = jTextNomeLoja3.getText();
                    String miniDescricaoProduto3 = jTextMiniDescricao3.getText();
                    String descricaoProduto3 = jTextDescricao3.getText();
                    String validade3 = jTextValidade3.getText();
                    int qtdProduto3 = 0;
                    double preco3 = 0;

                    if (nomeProduto3.length() > 0 && miniDescricaoProduto3.length() > 0 && descricaoProduto3.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade3)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd3.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco3.getText())) {

                                    qtdProduto3 = Integer.parseInt(jTextQtd3.getText());
                                    preco3 = Double.parseDouble(jTextPreco3.getText());

                                    item = new Item(nomeProduto3, miniDescricaoProduto3, descricaoProduto3, validade3, qtdProduto3, preco3);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item3 = true;
                                    ctd++;
                                    jTextNomeLoja3.setText("");// apagar cambo txt
                                    jTextMiniDescricao3.setText("");
                                    jTextDescricao3.setText("");
                                    jTextValidade3.setText("");
                                    jTextQtd3.setText("");
                                    jTextNomeLoja3.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }
                //item 4                     
                if (i == 4 && item4 == false) {
                    String nomeProduto4 = jTextNomeLoja4.getText();
                    String miniDescricaoProduto4 = jTextMiniDescricao4.getText();
                    String descricaoProduto4 = jTextDescricao4.getText();
                    String validade4 = jTextValidade4.getText();
                    int qtdProduto4 = 0;
                    double preco4 = 0;

                    if (nomeProduto4.length() > 0 && miniDescricaoProduto4.length() > 0 && descricaoProduto4.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade4)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd4.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco4.getText())) {

                                    qtdProduto4 = Integer.parseInt(jTextQtd4.getText());
                                    preco4 = Double.parseDouble(jTextPreco4.getText());

                                    item = new Item(nomeProduto4, miniDescricaoProduto4, descricaoProduto4, validade4, qtdProduto4, preco4);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item4 = true;
                                    ctd++;
                                    jTextNomeLoja4.setText("");// apagar cambo txt
                                    jTextMiniDescricao4.setText("");
                                    jTextDescricao4.setText("");
                                    jTextValidade4.setText("");
                                    jTextQtd4.setText("");
                                    jTextNomeLoja4.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }
                //item 5
                if (i == 5 && item5 == false) {
                    String nomeProduto5 = jTextNomeLoja5.getText();
                    String miniDescricaoProduto5 = jTextMiniDescricao5.getText();
                    String descricaoProduto5 = jTextDescricao5.getText();
                    String validade5 = jTextValidade5.getText();
                    int qtdProduto5 = 0;
                    double preco5 = 0;

                    if (nomeProduto5.length() > 0 && miniDescricaoProduto5.length() > 0 && descricaoProduto5.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade5)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd5.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco5.getText())) {

                                    qtdProduto5 = Integer.parseInt(jTextQtd5.getText());
                                    preco5 = Double.parseDouble(jTextPreco5.getText());

                                    item = new Item(nomeProduto5, miniDescricaoProduto5, descricaoProduto5, validade5, qtdProduto5, preco5);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item5 = true;
                                    ctd++;
                                    jTextNomeLoja5.setText("");// apagar cambo txt
                                    jTextMiniDescricao5.setText("");
                                    jTextDescricao5.setText("");
                                    jTextValidade5.setText("");
                                    jTextQtd5.setText("");
                                    jTextNomeLoja5.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }
                //item 6
                if (i == 6 && item6 == false) {
                    String nomeProduto6 = jTextNomeLoja6.getText();
                    String miniDescricaoProduto6 = jTextMiniDescricao6.getText();
                    String descricaoProduto6 = jTextDescricao6.getText();
                    String validade6 = jTextValidade6.getText();
                    int qtdProduto6 = 0;
                    double preco6 = 0;

                    if (nomeProduto6.length() > 0 && miniDescricaoProduto6.length() > 0 && descricaoProduto6.length() > 0) {

                        if (Utilitarios.validarDataValidade(validade6)) {

                            if (Utilitarios.ehNumeroValido(jTextQtd6.getText())) {

                                if (Utilitarios.ehDoubleValido(jTextPreco6.getText())) {

                                    qtdProduto6 = Integer.parseInt(jTextQtd6.getText());
                                    preco6 = Double.parseDouble(jTextPreco6.getText());

                                    item = new Item(nomeProduto6, miniDescricaoProduto6, descricaoProduto6, validade6, qtdProduto6, preco6);

                                    new AppDao().salvaItem(item, this.idVendedor);
                                    item6 = true;
                                    ctd++;
                                    jTextNomeLoja6.setText("");// apagar cambo txt
                                    jTextMiniDescricao6.setText("");
                                    jTextDescricao6.setText("");
                                    jTextValidade6.setText("");
                                    jTextQtd6.setText("");
                                    jTextNomeLoja6.setText("");

                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor Invalido!!");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Quantidade Invalida!!");

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Validade invalida ex: 12/11/2025 ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos do produto 1!!");
                    }
                }
            }

            if (ctd == qtdItem) {
                JOptionPane.showMessageDialog(null, "itens cadastrados com sucesso");
                dispose();
                new MinhaLoja(this.idVendedor).setVisible(true);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar Driver JDBC");
        } catch (SQLException ex) {

            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "item ja cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados: " + ex.getMessage());
            }
        } catch (NumberFormatException e) {
            // Trate o erro aqui, talvez exibindo uma mensagem ao usuário
            System.out.println("O valor selecionado não é um número válido.");
        }


    }//GEN-LAST:event_btnCadastrarItensActionPerformed

    private void jComboBoxQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQtdActionPerformed

        if (jComboBoxQtd.getSelectedItem().toString().equals("2")) {
            jPanelItem2.setVisible(true);
        } else if (jComboBoxQtd.getSelectedItem().toString().equals("3")) {
            jPanelItem2.setVisible(true);
            jPanelItem3.setVisible(true);
        } else if (jComboBoxQtd.getSelectedItem().toString().equals("4")) {
            jPanelItem2.setVisible(true);
            jPanelItem3.setVisible(true);
            jPanelItem4.setVisible(true);
        } else if (jComboBoxQtd.getSelectedItem().toString().equals("5")) {
            jPanelItem2.setVisible(true);
            jPanelItem3.setVisible(true);
            jPanelItem4.setVisible(true);
            jPanelItem5.setVisible(true);
        } else if (jComboBoxQtd.getSelectedItem().toString().equals("6")) {
            jPanelItem2.setVisible(true);
            jPanelItem3.setVisible(true);
            jPanelItem4.setVisible(true);
            jPanelItem5.setVisible(true);
            jPanelItem6.setVisible(true);
        } else {
            jPanelItem2.setVisible(false);
            jPanelItem3.setVisible(false);
            jPanelItem4.setVisible(false);
            jPanelItem5.setVisible(false);
            jPanelItem6.setVisible(false);
        }

    }//GEN-LAST:event_jComboBoxQtdActionPerformed

    private void jTextPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPreco1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarItem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarItem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarItem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarItem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarItens;
    private javax.swing.JComboBox<String> jComboBoxQtd;
    private javax.swing.JPanel jPanelItem;
    private javax.swing.JPanel jPanelItem1;
    private javax.swing.JPanel jPanelItem2;
    private javax.swing.JPanel jPanelItem3;
    private javax.swing.JPanel jPanelItem4;
    private javax.swing.JPanel jPanelItem5;
    private javax.swing.JPanel jPanelItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDescricao1;
    private javax.swing.JTextField jTextDescricao2;
    private javax.swing.JTextField jTextDescricao3;
    private javax.swing.JTextField jTextDescricao4;
    private javax.swing.JTextField jTextDescricao5;
    private javax.swing.JTextField jTextDescricao6;
    private javax.swing.JTextField jTextMiniDescricao1;
    private javax.swing.JTextField jTextMiniDescricao2;
    private javax.swing.JTextField jTextMiniDescricao3;
    private javax.swing.JTextField jTextMiniDescricao4;
    private javax.swing.JTextField jTextMiniDescricao5;
    private javax.swing.JTextField jTextMiniDescricao6;
    private javax.swing.JTextField jTextNomeLoja1;
    private javax.swing.JTextField jTextNomeLoja2;
    private javax.swing.JTextField jTextNomeLoja3;
    private javax.swing.JTextField jTextNomeLoja4;
    private javax.swing.JTextField jTextNomeLoja5;
    private javax.swing.JTextField jTextNomeLoja6;
    private javax.swing.JTextField jTextPreco1;
    private javax.swing.JTextField jTextPreco2;
    private javax.swing.JTextField jTextPreco3;
    private javax.swing.JTextField jTextPreco4;
    private javax.swing.JTextField jTextPreco5;
    private javax.swing.JTextField jTextPreco6;
    private javax.swing.JTextField jTextQtd1;
    private javax.swing.JTextField jTextQtd2;
    private javax.swing.JTextField jTextQtd3;
    private javax.swing.JTextField jTextQtd4;
    private javax.swing.JTextField jTextQtd5;
    private javax.swing.JTextField jTextQtd6;
    private javax.swing.JTextField jTextValidade1;
    private javax.swing.JTextField jTextValidade2;
    private javax.swing.JTextField jTextValidade3;
    private javax.swing.JTextField jTextValidade4;
    private javax.swing.JTextField jTextValidade5;
    private javax.swing.JTextField jTextValidade6;
    private javax.swing.JLabel jlDescricao1;
    private javax.swing.JLabel jlDescricao2;
    private javax.swing.JLabel jlDescricao3;
    private javax.swing.JLabel jlDescricao4;
    private javax.swing.JLabel jlDescricao5;
    private javax.swing.JLabel jlDescricao6;
    private javax.swing.JLabel jlMiniDescricao1;
    private javax.swing.JLabel jlMiniDescricao2;
    private javax.swing.JLabel jlMiniDescricao3;
    private javax.swing.JLabel jlMiniDescricao4;
    private javax.swing.JLabel jlMiniDescricao5;
    private javax.swing.JLabel jlMiniDescricao6;
    private javax.swing.JLabel jlNomeItem1;
    private javax.swing.JLabel jlNomeItem2;
    private javax.swing.JLabel jlNomeItem3;
    private javax.swing.JLabel jlNomeItem4;
    private javax.swing.JLabel jlNomeItem5;
    private javax.swing.JLabel jlNomeItem6;
    private javax.swing.JLabel jlPreco1;
    private javax.swing.JLabel jlPreco2;
    private javax.swing.JLabel jlPreco3;
    private javax.swing.JLabel jlPreco4;
    private javax.swing.JLabel jlPreco5;
    private javax.swing.JLabel jlPreco6;
    private javax.swing.JLabel jlQtd1;
    private javax.swing.JLabel jlQtd2;
    private javax.swing.JLabel jlQtd3;
    private javax.swing.JLabel jlQtd4;
    private javax.swing.JLabel jlQtd5;
    private javax.swing.JLabel jlQtd6;
    private javax.swing.JLabel jlQtdItensNaLoja;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JLabel jlTitulo3;
    private javax.swing.JLabel jlTitulo4;
    private javax.swing.JLabel jlTitulo5;
    private javax.swing.JLabel jlTitulo6;
    private javax.swing.JLabel jlValidade1;
    private javax.swing.JLabel jlValidade2;
    private javax.swing.JLabel jlValidade3;
    private javax.swing.JLabel jlValidade4;
    private javax.swing.JLabel jlValidade5;
    private javax.swing.JLabel jlValidade6;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
