/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dados.AppDao;
import dados.LojaVendedor;
import dados.Vendedor;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class CriarLoja extends javax.swing.JFrame {

    /**
     * Creates new form CriarLoja
     */
    private int idUsuario;

    public CriarLoja() {
        initComponents();
    }

    public CriarLoja(int idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jTxtSobreVC = new javax.swing.JTextField();
        jlSobreVC = new javax.swing.JLabel();
        jlbAlterar = new javax.swing.JLabel();
        jlNomeLoja = new javax.swing.JLabel();
        jTxtNomeLoja = new javax.swing.JTextField();
        jlMiniDescricaoLoja = new javax.swing.JLabel();
        jTxtMiniDescricao = new javax.swing.JTextField();
        jlCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jlLogo = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jlCapaLoja = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();
        jlCapaLoja1 = new javax.swing.JLabel();
        jComboBoxLocalRetirada = new javax.swing.JComboBox<>();
        btnCadastrarLoja = new javax.swing.JButton();
        jlHrVenda = new javax.swing.JLabel();
        jComboBoxHorarioVenda = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Loja");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/LOGO.png"))); // NOI18N

        jlSobreVC.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlSobreVC.setForeground(new java.awt.Color(0, 51, 102));
        jlSobreVC.setText("Descrição sobre a criacao da loja:");

        jlbAlterar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlbAlterar.setForeground(new java.awt.Color(255, 153, 51));
        jlbAlterar.setText("  Criar Loja");

        jlNomeLoja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeLoja.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeLoja.setText("                                  Nome Da Loja:");

        jlMiniDescricaoLoja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlMiniDescricaoLoja.setForeground(new java.awt.Color(0, 51, 102));
        jlMiniDescricaoLoja.setText("                  Mini Descrição Da Loja:");

        jlCategoria.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlCategoria.setForeground(new java.awt.Color(0, 51, 102));
        jlCategoria.setText("                                         Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação e Bebidas", "Moda e Vestuário", "Eletrônicos e Tecnologia", "Casa e Decoração", "Saúde e Beleza", "Esportes e Lazer", "Livros, Música e Papelaria", "Automotivo", "Infantil" }));

        jlLogo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlLogo.setForeground(new java.awt.Color(0, 51, 102));
        jlLogo.setText("                                                 Logo:");

        jlCapaLoja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlCapaLoja.setForeground(new java.awt.Color(0, 51, 102));
        jlCapaLoja.setText("                                   Capa Da Loja:");

        jlCapaLoja1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlCapaLoja1.setForeground(new java.awt.Color(0, 51, 102));
        jlCapaLoja1.setText("                          Ponto De Encontro:");

        jComboBoxLocalRetirada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portaria 1", "Portaria 2", "Biblioteca", "Praca Alimentacao 1", "Praca Alimentacao 2", "Praca Alimentacao 3", "Auditorio " }));

        btnCadastrarLoja.setBackground(new java.awt.Color(0, 153, 0));
        btnCadastrarLoja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCadastrarLoja.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarLoja.setText("Cadastrar Loja");
        btnCadastrarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLojaActionPerformed(evt);
            }
        });

        jlHrVenda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlHrVenda.setForeground(new java.awt.Color(0, 51, 102));
        jlHrVenda.setText("                            Horario de venda:");

        jComboBoxHorarioVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde", "Noite" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrarLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlSobreVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNomeLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlMiniDescricaoLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlCapaLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlCapaLoja1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlHrVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtSobreVC)
                            .addComponent(jTxtNomeLoja)
                            .addComponent(jTxtMiniDescricao)
                            .addComponent(jComboBoxCategoria, 0, 319, Short.MAX_VALUE)
                            .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLocalRetirada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxHorarioVenda, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbAlterar)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtSobreVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSobreVC, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeLoja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMiniDescricaoLoja)
                    .addComponent(jTxtMiniDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLogo)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCapaLoja)
                    .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCapaLoja1)
                    .addComponent(jComboBoxLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHrVenda)
                    .addComponent(jComboBoxHorarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnCadastrarLoja)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(914, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLojaActionPerformed

        try {
            String sobreVc = jTxtSobreVC.getText();
            String miniDescricao = jTxtMiniDescricao.getText();
            String nomeLoja = jTxtNomeLoja.getText();
            String categoria = jComboBoxCategoria.getSelectedItem().toString();
            String pontoDeEncontro = jComboBoxLocalRetirada.getSelectedItem().toString();
            String horarioVenda = jComboBoxHorarioVenda.getSelectedItem().toString();
            Vendedor vendedor1 = null;
            LojaVendedor loja1 = null;

            ResultSet usuario = new AppDao().buscarUsuario(this.idUsuario);// executa o select//import java.sql.ResultSet;
            // verificar se encontrou usuario informado
            if (usuario.next()) {// se encontrou

                //cria vendedor 
                vendedor1 = new Vendedor(usuario.getString("nome"), usuario.getString("email"),
                        usuario.getString("senha"), usuario.getString("cpf"), sobreVc);

                //cria loja do vendedor
                loja1 = new LojaVendedor(nomeLoja, miniDescricao,
                        categoria, pontoDeEncontro,horarioVenda,vendedor1);

            } else {// se nao encontrou
                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }

            if (sobreVc.length() > 0 && miniDescricao.length() > 0 && nomeLoja.length() > 0){
                new AppDao().salvarVendedor(vendedor1, idUsuario);
                new AppDao().salvarLoja(loja1, idUsuario);

                // avisar usuario se os dados foram salvos ou não
                JOptionPane.showMessageDialog(null, "Loja cadastrado com sucesso");

                dispose();
                new CriarItem(this.idUsuario).setVisible(true);
                
                jTxtNomeLoja.setText("");// apagar cambo txt
                jTxtSobreVC.setText("");
                jTxtMiniDescricao.setText("");
                jComboBoxCategoria.requestFocus();// apagar o combo box
                jComboBoxLocalRetirada.requestFocus();// apagar o combo box
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar Driver JDBC");
        } catch (SQLException ex) {

            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Loja ja cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarLoja;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxHorarioVenda;
    private javax.swing.JComboBox<String> jComboBoxLocalRetirada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtMiniDescricao;
    private javax.swing.JTextField jTxtNomeLoja;
    private javax.swing.JTextField jTxtSobreVC;
    private javax.swing.JLabel jlCapaLoja;
    private javax.swing.JLabel jlCapaLoja1;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlHrVenda;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlMiniDescricaoLoja;
    private javax.swing.JLabel jlNomeLoja;
    private javax.swing.JLabel jlSobreVC;
    private javax.swing.JLabel jlbAlterar;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
