/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dados.AppDao;
import dados.ReservaPedido;
import dados.Utilitarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import telas.Menu;

/**
 *
 * @author bruno.hgsilva3
 */
public class FinalizarCompra extends javax.swing.JFrame {

    /**
     * Creates new form FinalizarCompra
     */
    private ReservaPedido reserva;

    public FinalizarCompra() {
        initComponents();

    }

    public FinalizarCompra(ReservaPedido reserva) {
        initComponents();
        this.reserva = reserva;

        jTextNomeProduto.setText(reserva.getNomeProduto());
        jTextNomeProduto.setEnabled(false);

        jTextQtd.setEditable(false);

        jTextValor.setText(Double.toString(reserva.getValor()));
        jTextValor.setEditable(false);

        jTextNomeLoja.setText(reserva.getNomeLoja());
        jTextNomeLoja.setEditable(false);

        jTextNomeVendedor.setText(reserva.getNomeVendedor());
        jTextNomeVendedor.setEditable(false);

        jTextLocalRetirada.setText(reserva.getLocalDaReserva());
        jTextLocalRetirada.setEditable(false);

        if (reserva.getHorario().equals("Manha")) {
            jComboBoxHorario.addItem("7:40 a 8:00");
            jComboBoxHorario.addItem("9:40 a 10:00");
            jComboBoxHorario.addItem("11:40 a 12:00");
        } else if (reserva.getHorario().equals("Tarde")) {
            jComboBoxHorario.addItem("12:40 a 13:00");
            jComboBoxHorario.addItem("14:40 a 15:00");
            jComboBoxHorario.addItem("16:40 a 17:00");
        } else {
            jComboBoxHorario.addItem("18:40 a 19:00");
            jComboBoxHorario.addItem("20:40 a 21:00");
            jComboBoxHorario.addItem("22:40 a 23:00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlProduto = new javax.swing.JLabel();
        jTextNomeProduto = new javax.swing.JTextField();
        jlQtd = new javax.swing.JLabel();
        jTextQtd = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        btnReserva = new javax.swing.JButton();
        jlTitulo1 = new javax.swing.JLabel();
        jlTitulo2 = new javax.swing.JLabel();
        jlNomeLoja = new javax.swing.JLabel();
        jTextNomeLoja = new javax.swing.JTextField();
        jlNomeVendedor = new javax.swing.JLabel();
        jTextNomeVendedor = new javax.swing.JTextField();
        jlTitulo3 = new javax.swing.JLabel();
        jlDia = new javax.swing.JLabel();
        jTextDia = new javax.swing.JTextField();
        jlHorario = new javax.swing.JLabel();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jlLocalRetirada = new javax.swing.JLabel();
        jTextLocalRetirada = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/LOGO.png"))); // NOI18N

        jlTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo.setText("            Pedido");

        jlProduto.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlProduto.setForeground(new java.awt.Color(0, 51, 102));
        jlProduto.setText("Nome:");

        jTextNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeProdutoActionPerformed(evt);
            }
        });

        jlQtd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlQtd.setForeground(new java.awt.Color(0, 51, 102));
        jlQtd.setText("Quantidade:");

        jTextQtd.setText("1");

        jlValor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlValor.setForeground(new java.awt.Color(0, 51, 102));
        jlValor.setText("Valor:");

        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });

        btnReserva.setBackground(new java.awt.Color(0, 153, 0));
        btnReserva.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnReserva.setText("Finalizar Reserva");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        jlTitulo1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlTitulo1.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo1.setText("Produto");

        jlTitulo2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlTitulo2.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo2.setText("Vendedor");

        jlNomeLoja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeLoja.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeLoja.setText("Nome Loja:");

        jTextNomeLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeLojaActionPerformed(evt);
            }
        });

        jlNomeVendedor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNomeVendedor.setForeground(new java.awt.Color(0, 51, 102));
        jlNomeVendedor.setText("Vendedor:");

        jTextNomeVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeVendedorActionPerformed(evt);
            }
        });

        jlTitulo3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlTitulo3.setForeground(new java.awt.Color(255, 153, 51));
        jlTitulo3.setText("Retirada");

        jlDia.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDia.setForeground(new java.awt.Color(0, 51, 102));
        jlDia.setText("Data:");

        jTextDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiaActionPerformed(evt);
            }
        });

        jlHorario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlHorario.setForeground(new java.awt.Color(0, 51, 102));
        jlHorario.setText("Horario:");

        jlLocalRetirada.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlLocalRetirada.setForeground(new java.awt.Color(0, 51, 102));
        jlLocalRetirada.setText("Local:");

        jTextLocalRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLocalRetiradaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextLocalRetirada))
                    .addComponent(jlTitulo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNomeVendedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextDia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlQtd)
                                .addComponent(jlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNomeLoja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTitulo)
                .addGap(54, 54, 54)
                .addComponent(jlTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProduto)
                    .addComponent(jTextNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd)
                    .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeLoja)
                    .addComponent(jTextNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeVendedor)
                    .addComponent(jTextNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDia)
                    .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHorario)
                    .addComponent(jComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLocalRetirada))
                .addGap(18, 18, 18)
                .addComponent(btnReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed

        try {

            if (Utilitarios.validarDataValidade(jTextDia.getText())) {
                reserva.setData(jTextDia.getText());
                reserva.setHorario(jComboBoxHorario.getSelectedItem().toString());

                new AppDao().salvarReserva(this.reserva);

                JOptionPane.showMessageDialog(null, "Reservado com sucesso: \n" + reserva);
                dispose();
                new Menu(this.reserva.getIdComprador()).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Data Invalida!!");
            }
        } catch (ClassNotFoundException ex) {
            //import javax.swing.JOptionPane;
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar Driver JDBC");
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados:" + ex.getMessage());

        }

    }//GEN-LAST:event_btnReservaActionPerformed

    private void jTextNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeProdutoActionPerformed

    private void jTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jTextNomeLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeLojaActionPerformed

    private void jTextNomeVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeVendedorActionPerformed

    private void jTextDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiaActionPerformed

    private void jTextLocalRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLocalRetiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLocalRetiradaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();
        new Loja(reserva.getNomeLoja(), reserva.getIdComprador()).setVisible(true);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReserva;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDia;
    private javax.swing.JTextField jTextLocalRetirada;
    private javax.swing.JTextField jTextNomeLoja;
    private javax.swing.JTextField jTextNomeProduto;
    private javax.swing.JTextField jTextNomeVendedor;
    private javax.swing.JTextField jTextQtd;
    private javax.swing.JTextField jTextValor;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlLocalRetirada;
    private javax.swing.JLabel jlNomeLoja;
    private javax.swing.JLabel jlNomeVendedor;
    private javax.swing.JLabel jlProduto;
    private javax.swing.JLabel jlQtd;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JLabel jlTitulo3;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
