/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author bruno
 */
public class teste2 extends javax.swing.JFrame {

    /**
     * Creates new form teste2
     */
    public teste2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelLojas = new javax.swing.JPanel();
        loja1 = new javax.swing.JPanel();
        jlbImagem2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jlbValor2 = new javax.swing.JLabel();
        jLbTitulo2 = new javax.swing.JLabel();
        loja2 = new javax.swing.JPanel();
        jlbImagem11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jlbValor11 = new javax.swing.JLabel();
        jLbTitulo11 = new javax.swing.JLabel();
        loja3 = new javax.swing.JPanel();
        jlbImagem12 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jlbValor12 = new javax.swing.JLabel();
        jLbTitulo12 = new javax.swing.JLabel();
        loja4 = new javax.swing.JPanel();
        jlbImagem13 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jlbValor13 = new javax.swing.JLabel();
        jLbTitulo13 = new javax.swing.JLabel();
        loja5 = new javax.swing.JPanel();
        jlbImagem14 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jlbValor14 = new javax.swing.JLabel();
        jLbTitulo14 = new javax.swing.JLabel();
        loja6 = new javax.swing.JPanel();
        jlbImagem15 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jlbValor15 = new javax.swing.JLabel();
        jLbTitulo15 = new javax.swing.JLabel();
        loja7 = new javax.swing.JPanel();
        jlbImagem16 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jlbValor16 = new javax.swing.JLabel();
        jLbTitulo16 = new javax.swing.JLabel();
        loja8 = new javax.swing.JPanel();
        jlbImagem17 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jlbValor17 = new javax.swing.JLabel();
        jLbTitulo17 = new javax.swing.JLabel();
        loja9 = new javax.swing.JPanel();
        jlbImagem18 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jlbValor18 = new javax.swing.JLabel();
        jLbTitulo18 = new javax.swing.JLabel();
        loja10 = new javax.swing.JPanel();
        jlbImagem19 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jlbValor19 = new javax.swing.JLabel();
        jLbTitulo19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLojas.setBackground(new java.awt.Color(255, 255, 255));

        loja1.setBackground(new java.awt.Color(255, 255, 255));
        loja1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jlbImagem2.setText("Logo da loja");

        jButton3.setText("Entrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jlbValor2.setText("Avaliacao");

        jLbTitulo2.setText("Nome da loja");

        javax.swing.GroupLayout loja1Layout = new javax.swing.GroupLayout(loja1);
        loja1.setLayout(loja1Layout);
        loja1Layout.setHorizontalGroup(
            loja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja1Layout.createSequentialGroup()
                        .addComponent(jLbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja1Layout.createSequentialGroup()
                        .addComponent(jlbValor2)
                        .addContainerGap())))
        );
        loja1Layout.setVerticalGroup(
            loja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja1Layout.createSequentialGroup()
                        .addComponent(jLbTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jlbImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja2.setBackground(new java.awt.Color(255, 255, 255));
        loja2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jlbImagem11.setText("Logo da loja");

        jButton12.setText("Entrar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jlbValor11.setText("Avaliacao");

        jLbTitulo11.setText("Nome da loja");

        javax.swing.GroupLayout loja2Layout = new javax.swing.GroupLayout(loja2);
        loja2.setLayout(loja2Layout);
        loja2Layout.setHorizontalGroup(
            loja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja2Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja2Layout.createSequentialGroup()
                        .addComponent(jLbTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja2Layout.createSequentialGroup()
                        .addComponent(jlbValor11)
                        .addContainerGap())))
        );
        loja2Layout.setVerticalGroup(
            loja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja2Layout.createSequentialGroup()
                        .addComponent(jLbTitulo11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addComponent(jlbImagem11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja3.setBackground(new java.awt.Color(255, 255, 255));
        loja3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jlbImagem12.setText("Logo da loja");

        jButton13.setText("Entrar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jlbValor12.setText("Avaliacao");

        jLbTitulo12.setText("Nome da loja");

        javax.swing.GroupLayout loja3Layout = new javax.swing.GroupLayout(loja3);
        loja3.setLayout(loja3Layout);
        loja3Layout.setHorizontalGroup(
            loja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja3Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja3Layout.createSequentialGroup()
                        .addComponent(jLbTitulo12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja3Layout.createSequentialGroup()
                        .addComponent(jlbValor12)
                        .addContainerGap())))
        );
        loja3Layout.setVerticalGroup(
            loja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja3Layout.createSequentialGroup()
                        .addComponent(jLbTitulo12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton13))
                    .addComponent(jlbImagem12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja4.setBackground(new java.awt.Color(255, 255, 255));
        loja4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jlbImagem13.setText("Logo da loja");

        jButton14.setText("Entrar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jlbValor13.setText("Avaliacao");

        jLbTitulo13.setText("Nome da loja");

        javax.swing.GroupLayout loja4Layout = new javax.swing.GroupLayout(loja4);
        loja4.setLayout(loja4Layout);
        loja4Layout.setHorizontalGroup(
            loja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja4Layout.createSequentialGroup()
                        .addComponent(jButton14)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja4Layout.createSequentialGroup()
                        .addComponent(jLbTitulo13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja4Layout.createSequentialGroup()
                        .addComponent(jlbValor13)
                        .addContainerGap())))
        );
        loja4Layout.setVerticalGroup(
            loja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja4Layout.createSequentialGroup()
                        .addComponent(jLbTitulo13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton14))
                    .addComponent(jlbImagem13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja5.setBackground(new java.awt.Color(255, 255, 255));
        loja5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja5.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem14.setText("Logo da loja");

        jButton15.setText("Entrar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jlbValor14.setText("Avaliacao");

        jLbTitulo14.setText("Nome da loja");

        javax.swing.GroupLayout loja5Layout = new javax.swing.GroupLayout(loja5);
        loja5.setLayout(loja5Layout);
        loja5Layout.setHorizontalGroup(
            loja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(loja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja5Layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja5Layout.createSequentialGroup()
                        .addComponent(jLbTitulo14, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja5Layout.createSequentialGroup()
                        .addComponent(jlbValor14)
                        .addContainerGap())))
        );
        loja5Layout.setVerticalGroup(
            loja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja5Layout.createSequentialGroup()
                        .addComponent(jLbTitulo14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton15))
                    .addComponent(jlbImagem14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja6.setBackground(new java.awt.Color(255, 255, 255));
        loja6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja6.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem15.setText("Logo da loja");

        jButton16.setText("Entrar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jlbValor15.setText("Avaliacao");

        jLbTitulo15.setText("Nome da loja");

        javax.swing.GroupLayout loja6Layout = new javax.swing.GroupLayout(loja6);
        loja6.setLayout(loja6Layout);
        loja6Layout.setHorizontalGroup(
            loja6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja6Layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja6Layout.createSequentialGroup()
                        .addComponent(jLbTitulo15, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja6Layout.createSequentialGroup()
                        .addComponent(jlbValor15)
                        .addContainerGap())))
        );
        loja6Layout.setVerticalGroup(
            loja6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja6Layout.createSequentialGroup()
                        .addComponent(jLbTitulo15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton16))
                    .addComponent(jlbImagem15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja7.setBackground(new java.awt.Color(255, 255, 255));
        loja7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja7.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem16.setText("Logo da loja");

        jButton17.setText("Entrar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jlbValor16.setText("Avaliacao");

        jLbTitulo16.setText("Nome da loja");

        javax.swing.GroupLayout loja7Layout = new javax.swing.GroupLayout(loja7);
        loja7.setLayout(loja7Layout);
        loja7Layout.setHorizontalGroup(
            loja7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja7Layout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja7Layout.createSequentialGroup()
                        .addComponent(jLbTitulo16, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja7Layout.createSequentialGroup()
                        .addComponent(jlbValor16)
                        .addContainerGap())))
        );
        loja7Layout.setVerticalGroup(
            loja7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja7Layout.createSequentialGroup()
                        .addComponent(jLbTitulo16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addComponent(jlbImagem16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja8.setBackground(new java.awt.Color(255, 255, 255));
        loja8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja8.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem17.setText("Logo da loja");

        jButton18.setText("Entrar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jlbValor17.setText("Avaliacao");

        jLbTitulo17.setText("Nome da loja");

        javax.swing.GroupLayout loja8Layout = new javax.swing.GroupLayout(loja8);
        loja8.setLayout(loja8Layout);
        loja8Layout.setHorizontalGroup(
            loja8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja8Layout.createSequentialGroup()
                        .addComponent(jButton18)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja8Layout.createSequentialGroup()
                        .addComponent(jLbTitulo17, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja8Layout.createSequentialGroup()
                        .addComponent(jlbValor17)
                        .addContainerGap())))
        );
        loja8Layout.setVerticalGroup(
            loja8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja8Layout.createSequentialGroup()
                        .addComponent(jLbTitulo17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton18))
                    .addComponent(jlbImagem17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja9.setBackground(new java.awt.Color(255, 255, 255));
        loja9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja9.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem18.setText("Logo da loja");

        jButton19.setText("Entrar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jlbValor18.setText("Avaliacao");

        jLbTitulo18.setText("Nome da loja");

        javax.swing.GroupLayout loja9Layout = new javax.swing.GroupLayout(loja9);
        loja9.setLayout(loja9Layout);
        loja9Layout.setHorizontalGroup(
            loja9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja9Layout.createSequentialGroup()
                        .addComponent(jButton19)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja9Layout.createSequentialGroup()
                        .addComponent(jLbTitulo18, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja9Layout.createSequentialGroup()
                        .addComponent(jlbValor18)
                        .addContainerGap())))
        );
        loja9Layout.setVerticalGroup(
            loja9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja9Layout.createSequentialGroup()
                        .addComponent(jLbTitulo18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton19))
                    .addComponent(jlbImagem18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        loja10.setBackground(new java.awt.Color(255, 255, 255));
        loja10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        loja10.setPreferredSize(new java.awt.Dimension(340, 118));

        jlbImagem19.setText("Logo da loja");

        jButton20.setText("Entrar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jlbValor19.setText("Avaliacao");

        jLbTitulo19.setText("Nome da loja");

        javax.swing.GroupLayout loja10Layout = new javax.swing.GroupLayout(loja10);
        loja10.setLayout(loja10Layout);
        loja10Layout.setHorizontalGroup(
            loja10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loja10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbImagem19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loja10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja10Layout.createSequentialGroup()
                        .addComponent(jButton20)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja10Layout.createSequentialGroup()
                        .addComponent(jLbTitulo19, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(loja10Layout.createSequentialGroup()
                        .addComponent(jlbValor19)
                        .addContainerGap())))
        );
        loja10Layout.setVerticalGroup(
            loja10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loja10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loja10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loja10Layout.createSequentialGroup()
                        .addComponent(jLbTitulo19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton20))
                    .addComponent(jlbImagem19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLojasLayout = new javax.swing.GroupLayout(panelLojas);
        panelLojas.setLayout(panelLojasLayout);
        panelLojasLayout.setHorizontalGroup(
            panelLojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLojasLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(panelLojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loja10, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(loja9, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(loja7, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(loja4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loja3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loja5, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(loja2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loja1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loja6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(loja8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        panelLojasLayout.setVerticalGroup(
            panelLojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLojasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(loja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(loja5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loja6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(loja7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(loja8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loja9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(loja10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1540, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelLojas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 3000, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 3008));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLbTitulo11;
    private javax.swing.JLabel jLbTitulo12;
    private javax.swing.JLabel jLbTitulo13;
    private javax.swing.JLabel jLbTitulo14;
    private javax.swing.JLabel jLbTitulo15;
    private javax.swing.JLabel jLbTitulo16;
    private javax.swing.JLabel jLbTitulo17;
    private javax.swing.JLabel jLbTitulo18;
    private javax.swing.JLabel jLbTitulo19;
    private javax.swing.JLabel jLbTitulo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbImagem11;
    private javax.swing.JLabel jlbImagem12;
    private javax.swing.JLabel jlbImagem13;
    private javax.swing.JLabel jlbImagem14;
    private javax.swing.JLabel jlbImagem15;
    private javax.swing.JLabel jlbImagem16;
    private javax.swing.JLabel jlbImagem17;
    private javax.swing.JLabel jlbImagem18;
    private javax.swing.JLabel jlbImagem19;
    private javax.swing.JLabel jlbImagem2;
    private javax.swing.JLabel jlbValor11;
    private javax.swing.JLabel jlbValor12;
    private javax.swing.JLabel jlbValor13;
    private javax.swing.JLabel jlbValor14;
    private javax.swing.JLabel jlbValor15;
    private javax.swing.JLabel jlbValor16;
    private javax.swing.JLabel jlbValor17;
    private javax.swing.JLabel jlbValor18;
    private javax.swing.JLabel jlbValor19;
    private javax.swing.JLabel jlbValor2;
    private javax.swing.JPanel loja1;
    private javax.swing.JPanel loja10;
    private javax.swing.JPanel loja2;
    private javax.swing.JPanel loja3;
    private javax.swing.JPanel loja4;
    private javax.swing.JPanel loja5;
    private javax.swing.JPanel loja6;
    private javax.swing.JPanel loja7;
    private javax.swing.JPanel loja8;
    private javax.swing.JPanel loja9;
    private javax.swing.JPanel panelLojas;
    // End of variables declaration//GEN-END:variables
}
